-- ============================================================
-- NOTE: PDF storage now uses Cloudflare R2 (zero egress cost),
-- NOT Supabase Storage. You do NOT need to run this file.
--
-- See CLOUDFLARE_R2_SETUP.md for the R2 bucket + binding setup.
--
-- Supabase is only used for:
--   - Database (courses, subjects, papers metadata, solutions)
--   - Auth (admin login)
-- These are handled entirely by schema.sql.
-- ============================================================
